// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbGnvn-zYJi3jq2tnliRsUtHoneUfhitY',
    appId: '1:525221869357:web:c7eee025a0f87715b405a4',
    messagingSenderId: '525221869357',
    projectId: 'rescue35-951fc',
    authDomain: 'rescue35-951fc.firebaseapp.com',
    storageBucket: 'rescue35-951fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4s6Kd2Oi7UPL7RRQLUS5--0jmT9wcesw',
    appId: '1:525221869357:android:a1cb401ba93b87efb405a4',
    messagingSenderId: '525221869357',
    projectId: 'rescue35-951fc',
    storageBucket: 'rescue35-951fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIVioKixOlDcM0DLevonD_dyk-B0Gb8fM',
    appId: '1:525221869357:ios:cc9d7a62067266a9b405a4',
    messagingSenderId: '525221869357',
    projectId: 'rescue35-951fc',
    storageBucket: 'rescue35-951fc.firebasestorage.app',
    iosBundleId: 'com.example.rescue35',
  );
}
